import type { Metadata } from "next";
import "swiper/css";
import "swiper/css/free-mode";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/thumbs";
import { Footer, NavBar } from "../components";
import "../styles/globals.scss";

export const revalidate = 0;

export const metadata: Metadata = {
  title: "Tien Hung Chemicals",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className="relative">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
