import type { Metadata } from "next";
import "swiper/css";
import "swiper/css/pagination";
import "../styles/globals.scss";

export const metadata: Metadata = {
  title: "Freelancer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>{children}</body>
    </html>
  );
}
