declare namespace NodeJS {
  export interface ProcessEnv {
    NEXT_PUBLIC_API_ENDPOINT: string;
    NEXT_PUBLIC_GUST_TOKEN: string;
    NEXT_PUBLIC_FIREBASE_API_KEY: string;
    NEXT_PUBLIC_FIREBASE_DOMAIN: string;
    NEXT_PUBLIC_FIREBASE_PROJECT_ID: string;
    NEXT_PUBLIC_FIREBASE_BUCKET: string;
    NEXT_PUBLIC_FIREBASE_SENDER_ID: string;
    NEXT_PUBLIC_FIREBASE_APP_ID: string;
    NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: string;
  }
}
